'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18063
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.18063.
'
Namespace oCompanies
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="CompanyBinding", [Namespace]:="urn:company"),  _
     System.Xml.Serialization.SoapIncludeAttribute(GetType(CompanyType))>  _
    Partial Public Class Company
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private GetCompaniesOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.imagingXperts_eDocCloud_UpDown.My.MySettings.Default.imagingXperts_eDocCloud_UpDown_oCompanies_Company
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event GetCompaniesCompleted As GetCompaniesCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapRpcMethodAttribute("urn:pickupwsdl#GetBoxbyStatus", RequestNamespace:="urn:pickupwsdl", ResponseNamespace:="urn:pickupwsdl")>  _
        Public Function GetCompanies(ByVal token As String) As <System.Xml.Serialization.SoapElementAttribute("return")> CompanyType()
            Dim results() As Object = Me.Invoke("GetCompanies", New Object() {token})
            Return CType(results(0),CompanyType())
        End Function
        
        '''<remarks/>
        Public Overloads Sub GetCompaniesAsync(ByVal token As String)
            Me.GetCompaniesAsync(token, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub GetCompaniesAsync(ByVal token As String, ByVal userState As Object)
            If (Me.GetCompaniesOperationCompleted Is Nothing) Then
                Me.GetCompaniesOperationCompleted = AddressOf Me.OnGetCompaniesOperationCompleted
            End If
            Me.InvokeAsync("GetCompanies", New Object() {token}, Me.GetCompaniesOperationCompleted, userState)
        End Sub
        
        Private Sub OnGetCompaniesOperationCompleted(ByVal arg As Object)
            If (Not (Me.GetCompaniesCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent GetCompaniesCompleted(Me, New GetCompaniesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234"),  _
     System.SerializableAttribute(),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Xml.Serialization.SoapTypeAttribute([Namespace]:="urn:company")>  _
    Partial Public Class CompanyType
        
        Private row_idField As String
        
        Private company_nameField As String
        
        Private company_address1Field As String
        
        Private company_address2Field As String
        
        Private company_zipField As String
        
        Private fk_adminField As String
        
        Private company_phoneField As String
        
        Private company_faxField As String
        
        Private company_emailField As String
        
        Private fk_termsField As String
        
        Private creditlimitField As String
        
        '''<remarks/>
        <System.Xml.Serialization.SoapElementAttribute(DataType:="integer")>  _
        Public Property row_id() As String
            Get
                Return Me.row_idField
            End Get
            Set
                Me.row_idField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property company_name() As String
            Get
                Return Me.company_nameField
            End Get
            Set
                Me.company_nameField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property company_address1() As String
            Get
                Return Me.company_address1Field
            End Get
            Set
                Me.company_address1Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property company_address2() As String
            Get
                Return Me.company_address2Field
            End Get
            Set
                Me.company_address2Field = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property company_zip() As String
            Get
                Return Me.company_zipField
            End Get
            Set
                Me.company_zipField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fk_admin() As String
            Get
                Return Me.fk_adminField
            End Get
            Set
                Me.fk_adminField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property company_phone() As String
            Get
                Return Me.company_phoneField
            End Get
            Set
                Me.company_phoneField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property company_fax() As String
            Get
                Return Me.company_faxField
            End Get
            Set
                Me.company_faxField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property company_email() As String
            Get
                Return Me.company_emailField
            End Get
            Set
                Me.company_emailField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property fk_terms() As String
            Get
                Return Me.fk_termsField
            End Get
            Set
                Me.fk_termsField = value
            End Set
        End Property
        
        '''<remarks/>
        Public Property creditlimit() As String
            Get
                Return Me.creditlimitField
            End Get
            Set
                Me.creditlimitField = value
            End Set
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub GetCompaniesCompletedEventHandler(ByVal sender As Object, ByVal e As GetCompaniesCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class GetCompaniesCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As CompanyType()
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),CompanyType())
            End Get
        End Property
    End Class
End Namespace
